# Automatically generated by msquared.MGen on 2018-11-09 10:46:43.293228.
# DO NOT MODIFY.
ifdef VERBOSE
	AT=
else
	AT=@
endif

.PHONY: all
all: release debug

.PHONY: release
release: /home/pranav/C++/Stealth/SArgs/build/libsargs.so /home/pranav/C++/Stealth/SArgs/build/test

.PHONY: debug
debug:

.PHONY: libsargs.so
libsargs.so: /home/pranav/C++/Stealth/SArgs/build/libsargs.so

.PHONY: test
test: /home/pranav/C++/Stealth/SArgs/build/test

/home/pranav/C++/Stealth/SArgs/build/test: /home/pranav/C++/Stealth/SArgs/build/libsargs.so /home/pranav/C++/Stealth/SArgs/build/objs/test.2075983499174750070.o
	$(AT)echo -e "\e[92m\e[1mLinking /home/pranav/C++/Stealth/SArgs/build/test\e[0m"
	$(AT)g++ /home/pranav/C++/Stealth/SArgs/build/objs/test.2075983499174750070.o -o /home/pranav/C++/Stealth/SArgs/build/test /home/pranav/C++/Stealth/SArgs/build/libsargs.so -march=native -flto --std=c++17 -O3

/home/pranav/C++/Stealth/SArgs/build/objs/ArgumentParser.2075983499174750070.o: /home/pranav/C++/Stealth/SArgs/src/ArgumentParser.cpp /home/pranav/C++/Stealth/SArgs/include/ArgumentParser.hpp
	$(AT)mkdir -p /home/pranav/C++/Stealth/SArgs/build/objs
	$(AT)echo -e "\e[32mCompiling /home/pranav/C++/Stealth/SArgs/build/objs/ArgumentParser.2075983499174750070.o\e[0m"
	$(AT)g++ /home/pranav/C++/Stealth/SArgs/src/ArgumentParser.cpp -o /home/pranav/C++/Stealth/SArgs/build/objs/ArgumentParser.2075983499174750070.o -I/home/pranav/C++/Stealth/SArgs/include -march=native -flto --std=c++17 -O3 -c

.PHONY: clean
clean:
	$(AT)rm -rf /home/pranav/C++/Stealth/SArgs/build

/home/pranav/C++/Stealth/SArgs/build/libsargs.so: /home/pranav/C++/Stealth/SArgs/build/objs/ArgumentParser.2075983499174750070.o
	$(AT)echo -e "\e[92m\e[1mLinking /home/pranav/C++/Stealth/SArgs/build/libsargs.so\e[0m"
	$(AT)g++ /home/pranav/C++/Stealth/SArgs/build/objs/ArgumentParser.2075983499174750070.o -o /home/pranav/C++/Stealth/SArgs/build/libsargs.so -lstealthcore -flto -march=native -shared -fPIC -O3 --std=c++17

.PHONY: clean_test
clean_test:
	$(AT)rm -rf /home/pranav/C++/Stealth/SArgs/build/test /home/pranav/C++/Stealth/SArgs/build/objs/test.2075983499174750070.o

/home/pranav/C++/Stealth/SArgs/build/objs/test.2075983499174750070.o: /home/pranav/C++/Stealth/SArgs/test/test.cpp /home/pranav/C++/Stealth/SArgs/include/interfaces/SArgs /home/pranav/C++/Stealth/SArgs/include/ArgumentParser.hpp
	$(AT)mkdir -p /home/pranav/C++/Stealth/SArgs/build/objs
	$(AT)echo -e "\e[32mCompiling /home/pranav/C++/Stealth/SArgs/build/objs/test.2075983499174750070.o\e[0m"
	$(AT)g++ /home/pranav/C++/Stealth/SArgs/test/test.cpp -o /home/pranav/C++/Stealth/SArgs/build/objs/test.2075983499174750070.o -I/home/pranav/C++/Stealth/SArgs/include -march=native -flto --std=c++17 -O3 -c

.PHONY: clean_libsargs.so
clean_libsargs.so:
	$(AT)rm -rf /home/pranav/C++/Stealth/SArgs/build/libsargs.so /home/pranav/C++/Stealth/SArgs/build/objs/ArgumentParser.2075983499174750070.o

.PHONY: install_libsargs.so
install_libsargs.so: /home/pranav/C++/Stealth/SArgs/build/libsargs.so
	$(AT)echo -e "\e[34m\e[1mInstalling /home/pranav/C++/Stealth/SArgs/build/libsargs.so to /usr/local/lib/\e[0m"
	$(AT)sudo mkdir -p /usr/local/lib/
	$(AT)sudo cp -r /home/pranav/C++/Stealth/SArgs/build/libsargs.so /usr/local/lib/

.PHONY: install_SArgs
install_SArgs: /home/pranav/C++/Stealth/SArgs/./include/interfaces/SArgs
	$(AT)echo -e "\e[34m\e[1mInstalling /home/pranav/C++/Stealth/SArgs/./include/interfaces/SArgs to /usr/local/include/Stealth/\e[0m"
	$(AT)sudo mkdir -p /usr/local/include/Stealth/
	$(AT)sudo cp -r /home/pranav/C++/Stealth/SArgs/./include/interfaces/SArgs /usr/local/include/Stealth/

.PHONY: install
install: install_libsargs.so install_SArgs

.PHONY: uninstall_libsargs.so
uninstall_libsargs.so:
	$(AT)echo -e "\e[31m\e[1mUninstalling /usr/local/lib/libsargs.so\e[0m"
	$(AT)sudo rm -rf /usr/local/lib/libsargs.so
	$(AT)sudo rmdir --ignore-fail-on-non-empty /usr/local/lib/

.PHONY: uninstall_SArgs
uninstall_SArgs:
	$(AT)echo -e "\e[31m\e[1mUninstalling /usr/local/include/Stealth/SArgs\e[0m"
	$(AT)sudo rm -rf /usr/local/include/Stealth/SArgs
	$(AT)sudo rmdir --ignore-fail-on-non-empty /usr/local/include/Stealth/

.PHONY: uninstall
uninstall: uninstall_SArgs uninstall_libsargs.so

.PHONY: help
help:
	$(AT)echo "	all: Builds all targets specified in this Makefile."
	$(AT)echo "	release: Builds release targets specified in this Makefile."
	$(AT)echo "	debug: Builds debug targets specified in this Makefile."
	$(AT)echo "	libsargs.so: Builds libsargs.so"
	$(AT)echo "	test: Builds test"
	$(AT)echo "	clean: Removes the entire build directory."
	$(AT)echo "	clean_test: Removes test and its constituent object files."
	$(AT)echo "	clean_libsargs.so: Removes libsargs.so and its constituent object files."
	$(AT)echo "	install_libsargs.so: Installs /home/pranav/C++/Stealth/SArgs/build/libsargs.so to /usr/local/lib/."
	$(AT)echo "	install_SArgs: Installs /home/pranav/C++/Stealth/SArgs/./include/interfaces/SArgs to /usr/local/include/Stealth/."
	$(AT)echo "	install: Runs all other install targets."
	$(AT)echo "	uninstall_libsargs.so: Removes /usr/local/lib/libsargs.so and then removes the directory if it is empty."
	$(AT)echo "	uninstall_SArgs: Removes /usr/local/include/Stealth/SArgs and then removes the directory if it is empty."
	$(AT)echo "	uninstall: Runs all other uninstall targets."